Add Trophy
Samsung/UTopia pull request #5
Opened 2022-07-21 07:30 UTC by yuweol

Including aosp, tizen, and other famous opensource projects.

2022-07-21 07:39 UTC, sole2 approved these changes
LGTM :+1:

2022-07-21 08:05 UTC, musangk approved these changes, later dismissed
LGTM 👍

2022-07-21 08:13 UTC, sole2 requested changes
Found duplicate rows.

2022-07-21 08:13 UTC, sole2 commented on Trophy.md
> +[tizen/context](https://review.tizen.org/gerrit/#/admin/projects/platform/core/api/context) | [#255046(2)](https://review.tizen.org/gerrit/#/c/platform/core/api/context/+/255046/) | `other` |
There is duplicate row.
```suggestion
[tizen/context](https://review.tizen.org/gerrit/#/admin/projects/platform/core/api/context) | [#255046](https://review.tizen.org/gerrit/#/c/platform/core/api/context/+/255046/) | `other` |
```

2022-07-21 08:13 UTC, sole2 commented on Trophy.md
> +[tizen/system-settings](https://review.tizen.org/gerrit/#/admin/projects/platform/core/api/system-settings) | [#258170(2)](https://review.tizen.org/gerrit/#/c/platform/core/api/system-settings/+/2581
There is duplicate row.
```suggestion
[tizen/system-settings](https://review.tizen.org/gerrit/#/admin/projects/platform/core/api/system-settings) | [#258170](https://review.tizen.org/gerrit/#/c/platform/core/api/system-settings/+/258170/) | `nullchk` |
```

2022-07-21 10:14 UTC, yuweol commented on Trophy.md
> +[tizen/system-settings](https://review.tizen.org/gerrit/#/admin/projects/platform/core/api/system-settings) | [#258170(2)](https://review.tizen.org/gerrit/#/c/platform/core/api/system-settings/+/2581
Fixed 7d9f540

2022-07-21 10:14 UTC, yuweol commented on Trophy.md
> +[tizen/context](https://review.tizen.org/gerrit/#/admin/projects/platform/core/api/context) | [#255046(2)](https://review.tizen.org/gerrit/#/c/platform/core/api/context/+/255046/) | `other` |
Fixed 7d9f540

2022-07-21 10:15 UTC, sole2 approved these changes
LGTM :+1:

2022-07-22 01:04 UTC, musangk approved these changes

2022-07-22 01:18 UTC, merged